pool:
  name: Azure Pipelines

# Publish only if changes to csharp directory are committed to main.
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - csharp

steps:
  - template: csharp-build-steps.yaml

  - task: DotNetCoreCLI@2
    displayName: "DotNet Pack"
    inputs:
      command: 'pack'
      workingDirectory: 'csharp'
      projects: 'csharp/dirs.proj'
      verbosityPack: 'Minimal'
      packagesToPack: 'csharp/**/*.csproj'
      configuration: 'Release'
      packDirectory: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: Publish Build
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'

  # - task: DotNetCoreCLI@2
  #   displayName: "DotNet Push"
  #   inputs:
  #     command: 'push'
  #     workingDirectory: 'csharp'
  #     projects: 'csharp/dirs.proj'
  #     verbosity: 'Minimal'
  #     feedsToUse: Select
  #     nugetFeedType: 'internal'
  #     publishVstsFeed: VS
  #     publishPackageMetadata: true
  #     versioningScheme: 'byEnvVar'
  #     versionEnvVar: 'PackageVersion'
  #     packagesToPack: 'csharp/**/*.csproj'