pool:
  name: Azure Pipelines

# Publish only if changes to csharp directory are committed to main.
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - csharp

steps:
- template: csharp-build-steps.yaml
