pool:
  name: Azure Pipelines

# Publish only if changes to TypeScript directory are committed to main.
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - ts

pr: none

variables:
  Codeql.Enabled: true

steps:
- template: typescript-build-steps.yaml

- task: EsrpRelease@7
  inputs:
    connectedservicename: 'Devtunnels-esrp-cert-based'
    keyvaultname: 'tunnels-dev-kv'
    authcertname: 'esrp-cert'
    signcertname: 'esrp-sign'
    clientid: '142047f4-eda8-4853-8776-c2e81803ea13'
    intent: 'PackageDistribution'
    contenttype: 'npm'
    contentsource: 'folder'
    folderlocation: '$(System.DefaultWorkingDirectory)/ts/out/pkg'
    waitforreleasecompletion: true
    owners: 'jfullerton@microsoft.com'
    approvers: 'jasongin@microsoft.com, debekoe@microsoft.com, ilbiryuk@microsoft.com'
    serviceendpointurl: 'https://api.esrp.microsoft.com'
    mainpublisher: 'ESRPRELPACMAN'
    domaintenantid: '72f988bf-86f1-41af-91ab-2d7cd011db47'
