pool:
  name: Azure Pipelines

# Publish only if changes to TypeScript directory are committed to main.
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - ts

pr: none

variables:
  Codeql.Enabled: true

steps:
- template: typescript-build-steps.yaml
- task: EsrpRelease@5
  inputs:
    ConnectedServiceName: 'devtunnels-esrp'
    Intent: 'PackageDistribution'
    ContentType: 'npm'
    ContentSource: 'Folder'
    FolderLocation: '$(System.DefaultWorkingDirectory)/ts'
    WaitForReleaseCompletion: true
    Owners: 'jfullerton@microsoft.com'
    Approvers: 'jfullerton@microsoft.com'
    ServiceEndpointUrl: 'https://api.esrp.microsoft.com'
    MainPublisher: 'ESRPRELPACMAN'
    DomainTenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'
