pool:
  name: Azure Pipelines

# Publish only if changes to TypeScript directory are committed to main.
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - TypeScript

steps:
- template: typescript-build.yaml

- task: Npm@1
  displayName: 'Publish packages to internal feed'
  inputs:
    command: custom
    workingDir: TypeScript
    verbose: false
    customCommand: 'run publish'
