pool:
  name: Azure Pipelines

# Publish only if changes to TypeScript directory are committed to main.
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - ts

pr: none

steps:
- template: typescript-build-steps.yaml

- task: Npm@1
  displayName: 'Publish packages to external feed'
  inputs:
    command: custom
    workingDir: ts
    verbose: false
    customCommand: 'run publish --access public'
    customRegistry: useNpmrc
    customEndpoint: 'dev-tunnels-npm'
