name: Check Basis

on:
  pull_request:

jobs:
  no-basis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check for Basis
      run: |
        if grep -iR basis --exclude-dir=.github --exclude-dir=.git .; then
          exit 1
        else
          exit 0
        fi
