name: Check Basis

on:
  push:
  pull_request:

jobs:
  no-basis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check for Basis
      run: |
        grep -iR basis --exclude-dir=.github --exclude-dir=.git .
        [[ $? = 1 ]] && exit 0
        [[ $? = 0 ]] && exit 1
