name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Build
      run: cargo build --features connections --verbose --manifest-path=rs/Cargo.toml
    - name: Run tests
      run: cargo test --features connections --verbose --manifest-path=rs/Cargo.toml

