name: Test GitHub Workflow

on:
  workflow_dispatch:

jobs:
  debug-session:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install VS Code CLI
      run: |
        wget -qO- https://update.code.visualstudio.com/latest/linux-x64/stable | tar -xzf -
        sudo mv VSCode-linux-x64 /usr/local/vscode
        sudo ln -s /usr/local/vscode/code /usr/local/bin/code
        sudo chown root:root /usr/local/vscode/chrome-sandbox
        sudo chmod 4755 /usr/local/vscode/chrome-sandbox

    - name: Configure virtual display for VS Code
      run: |
        sudo apt-get update
        sudo apt-get install xvfb -y
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 &

    - name: Run VS Code Server
      run: |
        code tunnel --accept-server-license-terms --tunnel-id fun-hill-4v1r4gw.usw3 --host-token ${{ secrets.DEVTUNNEL_TOKEN }}

    #- name: Setup debug session
    #  uses: mxschmitt/action-tmate@v3
    #  with:
    #    timeout-minutes: 15
    #    detached: false
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
