name: Test GitHub Workflow

on:
  workflow_dispatch:

jobs:
  debug-session:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install VS Code CLI
      run: |
        curl -L 'https://update.code.visualstudio.com/latest/cli-linux-x64/stable' \
             -o vscode-cli.tar.gz
        mkdir -p ~/.vscode-cli
        tar -xzf vscode-cli.tar.gz -C ~/.vscode-cli --strip-components=1

    - name: Run VS Code Server
      run: |
        ~/.vscode-cli/bin/code version use stable --install-dir ~/.vscode-cli
        ~/.vscode-cli/bin/code-tunnel settings set security.workspace.trust.enabled false
        ~/.vscode-cli/bin/code-tunnel tunnel \
          --accept-server-license-terms \
          --tunnel-id fun-hill-4v1r4gw.usw3 \
          --host-token "${{ secrets.DEVTUNNEL_TOKEN }}"
