name: Test GitHub Workflow

on:
  workflow_dispatch:

jobs:
  debug-session:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install VS Code CLI
      run: |
        wget -qO- https://update.code.visualstudio.com/latest/linux-x64/stable | tar -xzf -
        sudo mv VSCode-linux-x64 /usr/local/vscode

    - name: Run VS Code Server
      run: |
        /usr/local/vscode/bin/code-tunnel tunnel \
          --accept-server-license-terms \
          --tunnel-id fun-hill-4v1r4gw.usw3 \
          --host-token "${{ secrets.DEVTUNNEL_TOKEN }}" \
          -- --disable-workspace-trust

    #- name: Setup debug session
    #  uses: mxschmitt/action-tmate@v3
    #  with:
    #    timeout-minutes: 15
    #    detached: false
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
